### ISSUE TITLE
Postgres install version not set consistently

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#120]
I merged the current head of master 42d9a1be7603aa505341a24ee032e8dae6c35ba0 into my "camper" branch and am now getting postgres install errors:

```
NOTIFIED: [sufia_dependencies/install | set postgres password] **************** 
changed: [default]

NOTIFIED: [sufia_dependencies/install | configure md5 security] *************** 
failed: [default] => {"checksum": "0ce3612cb31cc9be56a57b217becb4e3556e5cf6", "failed": true}
msg: Destination directory /etc/postgresql/9.4/main does not exist

FATAL: all hosts have already failed -- aborting
```

When I ssh into the system as built, postgres 9.3 installed but the task that's failing is looking for 9.4

```
$ ls /etc/postgresql
9.3
```

**Comment by mark-dce** [comment]
It seems like the postgres install task should be paraterized to match the md5 task

This just installs a recent-ish version 
https://github.com/curationexperts/ansible-hydra/blob/master/roles/sufia_dependencies/install/tasks/postgresql.yml#L3-L9 and doesn't specify a specific version:

```
- name: install postgresql packages
  apt: name={{ item }} state=present
  become: yes
  with_items:
  - postgresql
  - libpq-dev
  - python-psycopg2
  notify:
  - set postgres password
  - configure md5 security
  - restart postgres server
  - create pg hydra database
  - add pg hydra user
```

But the MD5 handler is written to use the version here:
https://github.com/curationexperts/ansible-hydra/blob/master/roles/sufia_dependencies/install/defaults/main.yml#L15

```
postgres_version: '9.4'
```

**Comment by mark-dce** [comment]
@acozine Here's the solution I'm using for now:

in roles/sufia_dependencies/tasks/postgressql.yml

```
- name: install postgresql packages
  apt: name={{ item }} state=present
  become: yes
  with_items:
  - postgresql
  - libpq-dev
  - python-psycopg2
  notify:
  - set postgres password
  - determine postgress directory  # <--- I've added this line in the notifications
  - configure md5 security
  - restart postgres server
  - create pg hydra database
  - add pg hydra user
```

and this in the handler

```
- name: show postgress version
  debug: var=postgres_version

- name: configure md5 security
  become: yes
  copy: src=pg_hba.conf dest=/etc/postgresql/{{ postgres_version.stdout }}/main/pg_hba.conf group=postgres owner=postgres backup=yes
```

It doesn't seem very elegant, but it works.  If you have a better idea, let me know; otherwise, let's merge this in because I think it's broken for Ubuntu right now.
