### ISSUE TITLE
Solr installer should set facts for solr reset

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#269]
I shouldn't get a hard fail because I haven't set solr_main_version.  Ideally, the solr installer task should be able to register what version was installed.  If for some reason the solr installer isn't run in a playbook, the solr restart should default to not running.

We could probably use a default like
when: {{ solr_main_version | default('not_installed') }} == 4

```
TASK [deploy : restart solr 4.x] *************************************************************************************************
fatal: [52.72.119.114]: FAILED! => {"failed": true, "msg": "The conditional check 'solr_main_version == 4' failed. The error was: error while evaluating conditional (solr_main_version == 4): 'solr_main_version' is undefined\n\nThe error appears to have been in '/Users/mark/Documents/workspace/_no_backup_/deploying_hydra/tufts-cm/ansible-hydra/roles/deploy/tasks/main.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: restart solr 4.x\n  ^ here\n"}
	to retry, use: --limit @/Users/mark/Documents/workspace/_no_backup_/deploying_hydra/tufts-cm/tufts-ubuntu.retry

PLAY RECAP ***********************************************************************************************************************
52.72.119.114              : ok=34   changed=27   unreachable=0    failed=1   
```

**Comment by acozine** [comment]
Oh, interesting. Can you give me a bit more context? It looks like this is happening on the `deploy` role. Are you running that role on a pre-existing box to deploy fresh code? Are you running it in the context of building a box? Which OS? What version of Solr are you trying to restart?

**Comment by mark-dce** [comment]
Yes - I'm running it in a deploy role.  I'm copying in my playbook here since the vars are in a private repo to keep them secure

```
# Config file to bulid a Ubuntu 16.04 LTS Xenial Xerus server for
# projects based on https://github.com/curationexperts/epigaea
# run the playbook with the command:
# "ansible-playbook -i hosts sample-ubuntu-16.yml"
# 
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - redaacted-vars.yml
  roles:
    - launch_ec2

- hosts: newboxes
  name: prep
  user: ubuntu
  gather_facts: false
  pre_tasks:
      - name: install python2 for ansible
        raw: sudo apt-get -y install python-simplejson

- hosts: newboxes
  name: configuration
  user: ubuntu
  vars_files:
    - redacted-vars.yml
  gather_facts: true
  roles:
    - { role: packages }
    - { role: mount_disks }
    - { role: set_timezone }
    - { role: system_setup }
    - { role: capistrano_setup }
    - { role: ruby }
    - { role: fedora }
    - { role: solr }
    - { role: frontend }
    - { role: sufia_dependencies/install }
    - { role: sufia_dependencies/config }
# sufia_dependencies must precede marmotta, which requires postgresql
    - { role: webserver/install }
    - { role: webserver/config }
    - { role: deploy }
```
