### ISSUE TITLE
Remove setup of shared Capistrano directories

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#292]
We should check if Capistrano will set up the shared directories it requires when run and that the following code is redundant: 

https://github.com/curationexperts/ansible-hydra/blob/master/roles/capistrano_setup/tasks/main.yml#L13-L20

```
- name: create cap directories
  become: yes
  file: path={{ item }} state=directory owner={{ capistrano_user }} group={{ capistrano_group }}
  with_items:
    - "{{ project_base }}/shared/config/initializers"
    - "{{ project_base }}/shared/log"
    - "{{ project_base }}/releases"
    - /home/{{ capistrano_user }}/.ssh
```
