### ISSUE TITLE
Set data volume for delete_on_termination

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#64]
I've just manually deleted three Instances and their separate opt volumes that don't delete automatically when you terminate the main instance.

Is it worth a playbook that tears down an instance build using launch_ec2?

**Comment by acozine** [comment]
There's a "delete on termination" setting for volumes. If we can use that by default it would be cleaner, I think.

**Comment by mark-dce** [comment]
Looks like delete_on_termination only applies to volumes created as part of the instance: 

I tried this

```
- name: attach volume to new instance
  ec2_vol:
    instance: "{{ ec2.instance_ids }}"
    region: "{{ ec2_region }}"
    device_name: /dev/sdf
    volume_size: 40
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    delete_on_termination: true
  register: ec2_vol
```

and got this

```
TASK: [launch_ec2 | attach volume to new instance] **************************** 
failed: [localhost] => {"failed": true}
msg: unsupported parameter for module: delete_on_termination

FATAL: all hosts have already failed -- aborting
```
